// Generated by CoffeeScript 1.6.3
(function() {
  var Experiment, Laboratory;

  Experiment = require("./experiment");

  Laboratory = require("./laboratory");

  module.exports = {
    Laboratory: Laboratory,
    Experiment: Experiment
  };

}).call(this);
