// Generated by CoffeeScript 1.6.3
(function() {
  var Experiment, Laboratory;

  Experiment = require("./experiment");

  Laboratory = (function() {
    function Laboratory(store) {
      this.store = store;
      this.experiments = {};
    }

    Laboratory.prototype.addExperiment = function(name) {
      var experiment;
      experiment = new Experiment(name, this.store);
      this.experiments[name] = experiment;
      return experiment;
    };

    Laboratory.prototype.get = function(name) {
      if (name == null) {
        throw new Error("Invalid Experiment Name");
      }
      return this.experiments[name];
    };

    Laboratory.prototype.run = function(name) {
      var _ref;
      return (_ref = this.get(name)) != null ? _ref.run() : void 0;
    };

    return Laboratory;

  })();

  module.exports = Laboratory;

}).call(this);
