// Generated by CoffeeScript 1.7.1
(function() {
  var MemoryStore;

  module.exports = MemoryStore = (function() {
    function MemoryStore() {
      this.results = {};
    }

    MemoryStore.prototype.get = function(experimentName) {
      return this.results[experimentName];
    };

    MemoryStore.prototype.addResult = function(experimentName, chosenVariantName) {
      return this.results[experimentName] = chosenVariantName;
    };

    return MemoryStore;

  })();

}).call(this);
